server:
  name: user-edge-service
  port: 8082

thrift:
  user:
    ip: 127.0.0.1
    port: 7911

# redis 相关配置文件
spring:
  application:
    name: spring-boot-redis
  jpa:
    database: mysql
    show-sql: true
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/test
  redis:
    password:

md5:
  salt: wwlnb

charsetName: utf-8